# Generated by Django 5.2.1 on 2025-05-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_user_id_auctionlisting_bid_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="photo_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
