# Generated by Django 5.2.1 on 2025-05-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auctionlisting_photo_url_alter_auctionlisting_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
