# Generated by Django 5.2.1 on 2025-05-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_auctionlisting_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="photo_url",
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
