# Generated by Django 5.2.1 on 2025-05-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_auctionlisting_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=23, max_digits=10),
            preserve_default=False,
        ),
    ]
