# Generated by Django 5.2.1 on 2025-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_bid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="is_active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
