# Generated by Django 5.2.1 on 2025-05-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_auctionlisting_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Books", "Books"),
                    ("Clothing", "Clothing"),
                    ("Home", "Home"),
                    ("Toys", "Toys"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
